#!/bin/bash

#SBATCH -p standard                       ## run on the standard partition
#SBATCH -A SMURGIA_LAB		      ## Specify lab account
#SBATCH -N 1                          ## run on a single node
#SBATCH -n 1                          ## request 1 task/cpu (1 CPU)
#SBATCH -o /pub/abrought/fermi-ml/examples/example3/slurmout/slurm-%a.out ##STDOUT
##SBATCH --mail-type=end,time_limit,fail,invalid_depend
##SBATCH --mail-user=abrought@uci.edu  ## use this email address
#SBATCH -t 10:00:00

source ~/.bash_profile
conda activate fermipy
python run.py ${SLURM_ARRAY_TASK_ID}
conda deactivate
