data:
  evfile: '/pub/abrought/fermi-ml/data/filelist.txt' # Contains 12 yrs of fermi data
  scfile: '/pub/abrought/fermi-ml/data/spacecraft.fits' # Contains info about telescope/response function
  ltcube: '/pub/abrought/fermi-ml/data/ltcube.fits' # Contains information about the exposure time at each location on the sky

binning:

  binsz      : 0.08
  npix :  [625,50]
  binsperdec : 10  
  coordsys   : 'GAL'
  proj : 'CAR'

selection:

  emin    : 1000 #MeV
  emax    : 100000 #MeV
  zmax    : 105
  evclass : 256 #P8R3_SOURCE
  evtype  : 3 
  tmin    : 239557417
  tmax    : 626835521
  glat    : 0
  glon    : 325      
  filter  : null
 
gtlike:

  edisp : True
  #SM irfs : 'P8R2_CLEAN_V6'
  irfs : 'P8R3_CLEAN_V2'
  #edisp_disable : ['isodiff']

model:

  src_roiwidth : 15 
  galdiff  : 
    - "/pub/abrought/fermi-ml/data/Modified_Maps/masked_reprojected_pion_decay_annuli_0_5.fits" # galdiff00
    - "/pub/abrought/fermi-ml/data/Modified_Maps/masked_reprojected_pion_decay_annuli_6_9.fits" # galdiff01
    - "/pub/abrought/fermi-ml/data/Modified_Maps/masked_reprojected_pion_decay_annuli_10_12.fits" # galdiff02
    - "/pub/abrought/fermi-ml/data/Modified_Maps/masked_reprojected_pion_decay_annuli_13_16.fits" # galdiff03
    - "/pub/abrought/fermi-ml/data/CO12_Baseline/masked_reprojected_pion_decay_annuli_0_5.fits" # galdiff04
    - "/pub/abrought/fermi-ml/data/CO12_Baseline/masked_reprojected_pion_decay_annuli_6_9.fits" # galdiff05
    - "/pub/abrought/fermi-ml/data/CO12_Baseline/masked_reprojected_pion_decay_annuli_10_12.fits" # galdiff06
    - "/pub/abrought/fermi-ml/data/CO12_Baseline/masked_reprojected_pion_decay_annuli_13_16.fits" # galdiff07
    - "/pub/abrought/fermi-ml/data/LAT_excess_template_datacube_modified.fits" # galdiff08
    - "/pub/abrought/fermi-ml/data/LAT_excess_template_datacube_smart.fits" # galdiff09

  #catalogs : ['3FGL']

fileio:
  usescratch: False

